-- 請在 Supabase 專案的 `SQL Editor` (左側選單) 貼上並執行以下指令：

-- 1. 建立 posts (消息) 資料表
CREATE TABLE posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 關閉 Row Level Security (RLS) 保護措施
-- 注意：這是為了讓前臺可以直接讀取與顯示測試資料所做的簡化設定
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;

-- 3. 插入兩筆測試資料
INSERT INTO posts (title, content, category) VALUES 
('綠綠因子春季健康講座開放報名', '迎接春季的新生活，我們將舉辦一系列的健康講座，由專業營養師與您分享飲食調整的黃金重點。歡迎大家踴躍參與！', '活動'),
('門市營業時間異動公告', '適逢連續假期，本週末各門市營業時間將統一調整為上午 10:00 至下午 18:00，造成您的不便敬請見諒。', '公告');
